### ISSUE TITLE
Flutter 2 compatibility

### ISSUE THREAD

**Issue by RZEROSTERN** [RZEROSTERN/editorjs-flutter#1]
I started this library with Flutter 1.2 version, unfortunately this affects to developments with Flutter 2 with compatibility issues. Right now in Hacktoberfest, you can contribute with:

- Compatibility with Flutter 2
- Null safety

Please message me or send me a mail to marco.ramirez@rzerocorp.com.mx if you want to contribute for assigning this issue to you.

**Comment by Dhi13man** [comment]
Please assign. Will try migrating to Null safety and Flutter 2. :)

**Comment by RZEROSTERN** [comment]
Thanks, Dhiman. I'll assign the issue for you.

**Comment by RZEROSTERN** [comment]
Issue closed. Thank you, @Dhi13man.
