### ISSUE TITLE
Make the button H1 to H6 has a heading format for each text

### ISSUE THREAD

**Issue by RZEROSTERN** [RZEROSTERN/editorjs-flutter#5]
This issue has been submitted last year, but is not done yet :(

The button in bottom bar that has H1 to H6 must implement the function of changing the paragraph style for each time you tap on it. It should have the same workflow as Zefyr has.

This button only will accept the 6 header styles standard.

**Comment by Prakhar9450** [comment]
Please assign me this issue

**Comment by RZEROSTERN** [comment]
Sure thing

**Comment by mnomanmemon** [comment]
Hi @RZEROSTERN, If this issue is still not assigned to anyone. Please assign it to me, I will take care of this

**Comment by RZEROSTERN** [comment]
@mnomanmemon right now this is assigned, but if you want to make an attempt to implement this, there will be no problem :). I'll assign you, too

**Comment by mnomanmemon** [comment]
Hi @RZEROSTERN , this issue has been fixed and [Pull Request](https://github.com/RZEROSTERN/editorjs-flutter/pull/7) has been generated as well. Thanks
