### ISSUE TITLE
Update for Flutter v3

### ISSUE THREAD

**Issue by RZEROSTERN** [RZEROSTERN/editorjs-flutter#6]
Update the library for having compatibility with Flutter v3

**Comment by WaniAthar** [comment]
which library

**Comment by RZEROSTERN** [comment]
Any that this project requires, the objective is to ensure is working with Flutter 3.

**Comment by mnomanmemon** [comment]
Hi @RZEROSTERN, If this issue is still not assigned to anyone. Please assign it to me, I will take care of this

**Comment by RZEROSTERN** [comment]
Sure thing

**Comment by mnomanmemon** [comment]
Hi @RZEROSTERN , this issue has been fixed and [Pull Request](https://github.com/RZEROSTERN/editorjs-flutter/pull/8) has been generated as well. Thanks
